version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      LANG: en_US.UTF-8
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # пробрасываем порт для подключения
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"  # пробрасываем порт для подключения
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
volumes:
  postgres_data:
