version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: "postgrtes"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # пробрасываем порт для подключения

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"  # пробрасываем порт для подключения

volumes:
  postgres_data:
