"""Add fields for User

Revision ID: 32558d23192a
Revises: c4fb3b2f60e9
Create Date: 2025-01-08 21:57:13.203369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32558d23192a'
down_revision: Union[str, None] = 'c4fb3b2f60e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('security_question', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('security_answer', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'security_answer')
    op.drop_column('user', 'security_question')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
